# Generated by Django 5.1.3 on 2024-11-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_data',
            name='target_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
