# Generated by Django 5.1.3 on 2024-11-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_to_do_data_target_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_data',
            name='task_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
